name: TriggerCreateTest

on:
  create:
#     branches: [ master ]
    tags: 
      - v

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: echo 'running amibranch'
      
#     - name: Notify Slack
#       run:  |
#         curl -X POST \
#         -H "Content-type:application/json" \
#         --data '{"text":"test"}' \
#         ${{ secrets.SLACK_WEBHOOK_URL }}
