name: TriggerCreateTest

on:
  create:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: echo 'running'
      
    - name: Slack notification
    - run:|
    curl -X POST -H 'Content-type: application/json' --data '{"text":"【テスト】Staging LP has been deployed!!"}' https://hooks.slack.com/services/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

